### ISSUE TITLE
Additional discussion on TPEs

### ISSUE THREAD

**Issue by ibarrien** [bayesoptbook/bayesoptbook.github.io#1]
**Description of issue**
Minor feature request: in section 8.11, more discussion on how tree parzen estimators (TPEs) are implemented might be an added bonus.

**Proposed resolution**
A simple example of TPEs in action -- e.g. illustrating use of inductive bias to define what the parent-child relationships are vs a uniform random approach where this relationship is not provided up front.
A brief explanation on how trees (parent-child rules) are defined in [Bergstra's implementation](https://github.com/jaberg/hyperopt/blob/master/hyperopt/tpe.py).
See also how abstract syntax trees are used in this (hyperopt) [implementation](https://github.com/hyperopt/hyperopt/blob/175148302b3611ee0dc6aca9438dc582e21c0d43/hyperopt/tpe.py#L468).

**Additional context**
Adding such discussion could be an added bonus but may not fit the flow of the discussion in section 8.11

**Additional context**
Thanks for this neat monograph!

**Comment by bayesoptbook** [comment]
Perhaps the main idea behind TPEs could be told in a (marginal?) figure. I'll give it some thought.

**Comment by bayesoptbook** [comment]
I took a stab at reframing this subsection entirely in light of #10; a draft is in the most recent version of the book.
