### ISSUE TITLE
Links in the preface are incorrect

### ISSUE THREAD

**Issue by ScriptDevil** [bayesoptbook/bayesoptbook.github.io#15]
**Describe the erratum**
In the preface, on page x, there are 2 links to bayesoptbook.com which in reality links to https://bayesoptbook.com//book/bayesoptbook.com and github.com/bayesoptbook/bayesoptbook.github.io which links to https://bayesoptbook.com//book/github.com/bayesoptbook/bayesoptbook.github.io

This is most likely due to not using https:// making them relative to the current page. - this can be observed when opening the PDF in the browser itself rather than a system viewer,

**Version and Location**

- Draft as of 27 October 2021.
- x

**Proposed correction**
Use https://

**Additional context**
May not manifest if using a system PDF viewer. I used the builtin firefox viewer which seems to interpret protocol-less links as relative to the current page.

**Comment by bayesoptbook** [comment]
The targets are now fully qualified URLs!
