### ISSUE TITLE
Small nit: missing space after comma

### ISSUE THREAD

**Issue by EugenHotaj** [bayesoptbook/bayesoptbook.github.io#17]
**Describe the erratum**
As title.

**Version and Location**
November 13, 2021 version, page 71.

**Screenshots**
<img width="597" alt="Screen Shot 2021-12-06 at 8 57 30 AM" src="https://user-images.githubusercontent.com/6221162/144858764-e963609d-d201-44f0-9841-b49c98033181.png">

**Additional context**
Just a small nit :)

**Comment by bayesoptbook** [comment]
Thank you, will be fixed in the next draft (should post today)!
