### ISSUE TITLE
Exercises for the textbook chapters?

### ISSUE THREAD

**Issue by asp2204** [bayesoptbook/bayesoptbook.github.io#18]
Hi there, I thought your upcoming textbook on Bayesian Optimization looked promising, and I was wondering if there were any plans to add exercises to each chapter? (I tried looking around and ctrl+f'ing the textbook file and associated websites and don't think I missed them). I work in computational neuroscience, so I'm not necessarily the target audience for your book, but I would like to read it eventually, and things stick much better for me if a book has exercises / some additional food for thought.

Thanks.

**Comment by bayesoptbook** [comment]
I sympathize with your concern, but I'm afraid this isn't in the cards. At least not for this edition!
