### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by kei-mo** [bayesoptbook/bayesoptbook.github.io#19]
**Describe the erratum**
X in eq. 11.3 should be calligraphic font?

**Version and Location**
Please provide:
- 8 December 2021
- p. 250

**Proposed correction**

X in eq. 11.3 
![image](https://user-images.githubusercontent.com/12568774/148507007-f14e0889-e414-4880-8c60-430a995e24dd.png)
->
![image](https://user-images.githubusercontent.com/12568774/148507110-0face97f-1bcf-462e-83d2-7bbcef8e474b.png)

`x \in X \cap \matcal{F}` -> `x \in \mathcal{X} \cap \mathcal{F}` 

**Screenshots**
If applicable, add screenshots to help explain the problem.

![image](https://user-images.githubusercontent.com/12568774/148506244-47062661-20f0-4517-a679-2d2d01e5024a.png)

**Comment by bayesoptbook** [comment]
This is correct as written; we are looking for the best point observed (that is, in **x**) that is also feasible.
