### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by kei-mo** [bayesoptbook/bayesoptbook.github.io#20]
**Describe the erratum**
Missing period

**Version and Location**
Please provide:
- 8 December 2021
- p.252 line 5

**Proposed correction**
space of the decision problem -> space of the decision problem.

**Screenshots**
If applicable, add screenshots to help explain the problem.
![image](https://user-images.githubusercontent.com/12568774/148513977-95d908da-5267-4dc6-b215-51891bdd6c6c.png)

**Comment by bayesoptbook** [comment]
Thank you! This correction will appear in the next draft.
