### ISSUE TITLE
Typo pg 48

### ISSUE THREAD

**Issue by cgoble001** [bayesoptbook/bayesoptbook.github.io#21]
**Describe the erratum**
A clear and concise description of the erratum.

On page 47-48 "were" instead of "where".
"Then we can marginalize the unknown constant mean exactly to derive
the marginal Gaussian process **were** the uncertainty in the mean has been absorbed into the prior
covariance function"

**Version and Location**
Please provide:
8th Dec 2021, pg 48

**Comment by bayesoptbook** [comment]
Thank you! This correction will appear in the next draft.
