### ISSUE TITLE
Reference to figure is linked to an equation instead of  the figure (pg 163)

### ISSUE THREAD

**Issue by cgoble001** [bayesoptbook/bayesoptbook.github.io#22]
**Describe the erratum**
On pg 163:
"Geometrically, the situation collapses to that in figure 8.9"
Here figure 8.9 is linked to equation 8.9. I believe you, instead, might mean to link figure 8.1. But cannot be certain as I have not yet reached pg 174 where figure 8.9 is found.

**Version and Location**
8th December 2021

**Comment by bayesoptbook** [comment]
Thank you; this has been fixed and will appear in the next draft!
