### ISSUE TITLE
Typo in bibliographic reference

### ISSUE THREAD

**Issue by rafaol** [bayesoptbook/bayesoptbook.github.io#23]
**Describe the erratum**
Thanks for the great book! I'd just like to point out a typo on the reference for Oliveira et al. (2019). The publication venue is not ICML 2019, but AISTATS 2019 instead.

**Version and Location**
- Date: Draft as of 11 January 2022
- Location: pages 279 and 343

**Proposed correction**
Proposed changes:
- Book title: _Proceedings of the 36th International Conference on Machine Learning
(icml 2019)_ -> _Proceedings of the 22nd International Conference on Artificial Intelligence and Statistics (AISTATS 2019)_
- Volume: "Vol. 97" -> "Vol. 89"

Here is the official BibTex from the PMLR website, case that helps:

```
@InProceedings{pmlr-v89-oliveira19a,
  title = 	 {Bayesian optimisation under uncertain inputs},
  author =       {Oliveira, Rafael and Ott, Lionel and Ramos, Fabio},
  booktitle = 	 {Proceedings of the Twenty-Second International Conference on Artificial Intelligence and Statistics},
  pages = 	 {1177--1184},
  year = 	 {2019},
  editor = 	 {Chaudhuri, Kamalika and Sugiyama, Masashi},
  volume = 	 {89},
  series = 	 {Proceedings of Machine Learning Research},
  month = 	 {16--18 Apr},
  publisher =    {PMLR},
  url = 	 {https://proceedings.mlr.press/v89/oliveira19a.html}
}

```

**Comment by bayesoptbook** [comment]
So sorry about that Rafael! I just fixed the issue and pushed out a new version. Please double check ;)

**Comment by rafaol** [comment]
Thanks! It's all good now.
