### ISSUE TITLE
Missing label for x_4 in figure 11.11

### ISSUE THREAD

**Issue by neildhir** [bayesoptbook/bayesoptbook.github.io#24]
**Describe the erratum**
The label x_4 is missing from figure 11.11 on page 270. Reference is made to x_4.

**Version and Location**
Please provide:
- 27th of Jan 2022
- p 270

**Proposed correction**
Just add in the label $x_4$

**Screenshots**
It's fairly obvious from the figure what's missing.

**Additional context**
None. Loving the book so far. Great job.

**Comment by bayesoptbook** [comment]
Thank you for this. I've updated the figure but the book is currently in a frozen state as it undergoes copyediting. So it might take a bit for this correction to go live.
