### ISSUE TITLE
Typo (p. 116)

### ISSUE THREAD

**Issue by Jiangyan-Zhao** [bayesoptbook/bayesoptbook.github.io#26]
**Version and Location**
Please provide:
- 27 January 2022
- p. 116

**Proposed correction**
is is -> is

**Screenshots**
![1646409094(1)](https://user-images.githubusercontent.com/44356918/156796077-a2c39cb1-f60a-440a-aeed-eb43f16b4026.jpg)

**Comment by bayesoptbook** [comment]
Thank you! I've fixed this in my local revision. The book is currently "on hold" while undergoing copyediting, so it will take a while to appear.
