### ISSUE TITLE
Typo (P. 177)

### ISSUE THREAD

**Issue by Jiangyan-Zhao** [bayesoptbook/bayesoptbook.github.io#29]
**Version and Location**
- 27 January 2022
- pg. 177

**Proposed correction**
... of the we will ... -> ... of the analysis, we will ...

**Screenshots**
![image](https://user-images.githubusercontent.com/44356918/159121466-b9468627-2278-4c11-925a-3db2ab87daa5.png)

**Comment by bayesoptbook** [comment]
Thank you, I have modified my local revision to say "...for the remainder of this discussion..."
