### ISSUE TITLE
It would be better if it were stated in a way that maximizes PI on page 171

### ISSUE THREAD

**Issue by Jiangyan-Zhao** [bayesoptbook/bayesoptbook.github.io#31]
**Version and Location**
- 27 January 2022
- p. 171

**Proposed resolution**
The first thing to be clear is that this is definitely not an error, but it would be better if it were stated in a way that maximizes PI, since the acquisition functions usually take the maximization approach.

**Screenshots**
![image](https://user-images.githubusercontent.com/44356918/159122126-5b9d4427-8da7-4697-a3a3-137fd503d05d.png)

**Comment by bayesoptbook** [comment]
I considered this at one point. What I don't like is that there'd be a sign flip -- as written the (τ - μ) / σ term remains constant above/at/below (8.26), whereas rewriting as an argmax would require some (μ - τ) / σ and/or -β terms, neither of which feels "natural." However, one might argue that argmin doesn't feel natural either!

I think I'll probably leave as is, which I judge to be the lesser of two evils.
