### ISSUE TITLE
Typo (p.204)

### ISSUE THREAD

**Issue by Jiangyan-Zhao** [bayesoptbook/bayesoptbook.github.io#33]
**Version and Location**
- 27 January 2022
- p. 204 

**Proposed correction**
Section 2.8, p.301 -> Section 2.8, **p.39** or Section **B.1**, p.301

**Screenshots**
![image](https://user-images.githubusercontent.com/44356918/160589918-dcc16a4b-e543-447e-bbb8-1417f7141ef7.png)

**Comment by bayesoptbook** [comment]
Thank you; I have fixed this locally to point to section 2.8, p. 39. This will take a while to go live while the book undergoes copyediting.
