### ISSUE TITLE
Typo (P. 125) 

### ISSUE THREAD

**Issue by Ryan-Rhys** [bayesoptbook/bayesoptbook.github.io#36]
**Describe the erratum**
Typo pg. 125

**Version and Location**
Please provide:
- 27 Jan 2022
- page 125

**Proposed correction**
"lead" -> "led"

**Screenshots**
![typo_page_125](https://user-images.githubusercontent.com/20681951/180781688-889bd63d-ca80-4a0b-ad74-3a2310e1019e.png)

**Comment by bayesoptbook** [comment]
Thank you! This will be fixed in the next version
