### ISSUE TITLE
Add reference

### ISSUE THREAD

**Issue by euphoria0-0** [bayesoptbook/bayesoptbook.github.io#40]
**Description of issue**
A clear and concise description of the perceived problem/missing content.
In page 197, TPE (j. bergstra et al.) in density ratio estimation part, it refered 73-75. But it would be nice that it contains the latest paper, "A General Recipe for Likelihood-free Bayesian Optimization" [J. Song et al.]. This paper proved that the density ratio is Probaibility of Improvement not Expected Improvement.

**Proposed resolution**
A clear and concise description of what you'd like to see.
Add this in footnote 74: "J. Song et al., proved that it is the probability of improvement"

**Additional context**

**Additional context**

**Comment by georgedeath** [comment]
See https://github.com/bayesoptbook/bayesoptbook.github.io/issues/10.

**Comment by euphoria0-0** [comment]
right. The paper that I mentioned is (almost) same with the paper mentioned in the thread (NeurIPS workshop paper). The authors are the same. Thank you for reply!

**Comment by bayesoptbook** [comment]
To the best of my knowledge this result first appeared in early November 2021 in the issue linked by @georgedeath, and was added to the book in mid-November of that year. That predates the workshop paper by 4-6 weeks. Song, et al. discovered the same fact contemporaneously, and they in fact acknowledged this in the 2022 paper, citing the book.
