### ISSUE TITLE
Minor typo? "generalized" adversarial network

### ISSUE THREAD

**Issue by ltiao** [bayesoptbook/bayesoptbook.github.io#41]
**Describe the erratum**

Typo: "generalized" adversarial network

**Version and Location**
Please provide:
- the date in running footer of the draft in which the erratum appears: no running footer visible
- the page number on which the erratum appears: 199

**Proposed correction**

generalized -> generative

**Screenshots**

![Screenshot from 2023-06-12 20-18-16](https://github.com/bayesoptbook/bayesoptbook.github.io/assets/1112238/d338ef19-98d1-4ac9-86eb-83a984ffad4c)

**Additional context**

None

**Comment by bayesoptbook** [comment]
fixed in the current version, thank you!
