### ISSUE TITLE
Typo p.90

### ISSUE THREAD

**Issue by dothit** [bayesoptbook/bayesoptbook.github.io#42]
Possibly wrong use of the word "tenant" .

**Version and Location**
- No date can be provided, the semantic error occurs in the version provided on the website.
- Near the bottom of p.90.

**Proposed correction**
Instead of
```
This procedure for acting optimally under uncertainty ... is the central tenant of Bayesian decision making.
```
it should say
```
This procedure for acting optimally under uncertainty ... is the central tenet of Bayesian decision making.
```
to likely carry the actually intended meaning. Apparently this happens often enough that it warrants an article by [Merriam-Webster](https://www.merriam-webster.com/grammar/tenant-vs-tenet-difference-usage)?

(Awesome book, btw.)

**Comment by bayesoptbook** [comment]
Yikes, embarrassing. Fixed. Thanks!
