### ISSUE TITLE
Typo (p.17)

### ISSUE THREAD

**Issue by chrisyeh96** [bayesoptbook/bayesoptbook.github.io#43]
**Describe the erratum**

The book says
> computing $p(\boldsymbol\phi' \mid \mathbf{x}')$ then marginalizing $\mathbf{x}' \setminus \mathbf{x}$ (A.13).

However, I think it should instead say
> computing $p(\boldsymbol\phi' \mid \mathbf{x}')$ then marginalizing $\boldsymbol\phi' \setminus \boldsymbol\phi$ (A.13).

$\mathbf{x}$ and $\mathbf{x}'$ in this case are not random and therefore cannot be marginalized. The distribution is over $\boldsymbol\phi$ and $\boldsymbol\phi'$.

**Version and Location**

I downloaded the book PDF from the https://bayesoptbook.com/ website on 2023-11-20. According to the PDF metadata, the PDF was created on 2023-10-17.

Page number: p.17 in the book, or p.35 in the PDF

**Proposed correction**
See above.

**Comment by bayesoptbook** [comment]
Yes, you are correct! I will fix when I can, adding this confirmation here for anyone else looking at this.

**Comment by bayesoptbook** [comment]
This has (finally) been fixed, thanks again.
