### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by mjzhu-p** [bayesoptbook/bayesoptbook.github.io#45]
In figure caption of Figure 1.5, page 12

'....., starting from the posterior in Figure **1.4**,....'

change Figure 1.4 --> Figure 1.3

**Comment by bayesoptbook** [comment]
thank you, will fix

**Comment by bayesoptbook** [comment]
Fixed in https://github.com/bayesoptbook/bayesoptbook.github.io/commit/4d50efd68587ee8337aba83889270394f7591884, thanks again!
