### ISSUE TITLE
More detailed explanations or suggested references for 'Bayesian inference of the objective function'  

### ISSUE THREAD

**Issue by mjzhu-p** [bayesoptbook/bayesoptbook.github.io#46]
Dear Dr. Roman Garnett,

Thank you for the nice book on BO. 

I am writing to check if it would be possible for you to provide some more detailed explanations on the footnote 9 in Chapter 1 (page 9) in the subsection of 'Bayesian inference of the objective function'. Specifically, I am a bit confused on how to obtain the posterior on $\phi_*$. Do you mind explictly note the joint prior and conditioning in this case. Also, are there any suggested readings on the topic of 'Bayesian inference of the objective function' that you would suggest? 

Thank you,
Mengjia

**Comment by bayesoptbook** [comment]
This step is described in detail for Gaussian processes in the following chapter. It's hard to say anything specific in general beyond what's already written in the margin. We can define the posterior process by describing its finite-dimensional distributions, and an arbitrary FDD can be found via the given computation. Give the first half of chapter 2 a read and see if it helps.
