### ISSUE TITLE
Typo p. 229

### ISSUE THREAD

**Issue by chrisyeh96** [bayesoptbook/bayesoptbook.github.io#50]
**Describe the erratum**

I believe there may be a typo in the direction of an inequality. The book writes,
> Since the algorithm always maximizes the upper confidence bound in each iteration, we always have $u_i \leq u_i^*$. [...]

I believe that this should say $u_i \geq u_i^*$, because $u_i$ is the UCB corresponding to the selected point $x_i$. Otherwise, $x_i$ would not have been selected.

Further evidence comes on the same page, where the book writes,
> where we have added $u_i - u_i^* \geq 0$ to each term and rearranged.

This suggests that $u_i \geq u_i^*$.

**Version and Location**

Book version: downloaded from https://bayesoptbook.com/book/bayesoptbook.pdf on 2024-03-06.
Page: 229

**Comment by bayesoptbook** [comment]
Thank you, you are of course correct. Fixed by https://github.com/bayesoptbook/bayesoptbook.github.io/commit/e092d8ae6c016c1a2cd7ed8c2ca546c0d51d6742.
