### ISSUE TITLE
Clarify Kullback-Leibler divergence equivalence proof (p. 138, side note 22)

### ISSUE THREAD

**Issue by mjzhu-p** [bayesoptbook/bayesoptbook.github.io#51]
I am trying to understand the equivalence proof of two information gains when used as an optimization policy in maximizing mutual information, presented on page 138 with side note number 22.

In the text, it notes:
![image](https://github.com/bayesoptbook/bayesoptbook.github.io/assets/58212945/c94dd37f-3b6d-46e5-8085-c01fc52e8952)
 
Could you clarify why, when taking the expectation, you only need to condition on $D$, rather than $D'$ ?
A second question is related to the form of $u(D')$, is it defined as $u(D') = D_{KL}[p(\omega|D') || p(\omega)]$ or $u(D') = D_{KL}[p(\omega|D') || p(\omega|D)]$ ? I would assume the latter, but from the proof, it seems to be the previous one? I probably missed some details here, but I would really appreciate it if you could provide some more details. Thank you.

If there are any recommended readings, could you also direct me to them? I am having some trouble finding relevant papers/documents. Thank you!

**Comment by bayesoptbook** [comment]
Sorry that some details were swept under the rug here:

    E[ ∫ p(ω | D') log p(ω) dω | x, D ]
	    = ∫ [ ∫ p(ω | D') log p(ω) dω ] p(y | x, D) dy                     [expectation wrt y | x, D]
	    = ∫ [ ∫ p(ω, y | x, D) / p(y | x, D) log p(ω) dω ] p(y | x, D) dy  [expanding p(ω | D')]
	    = ∫ [ ∫ p(ω, y | x, D) log p(ω) dω ] dy	                       [cancelling p(y | x, D), which doesn't depend on ω]
	    = ∫ [ ∫ p(ω, y | x, D) dy ] log p(ω) dω                            [swapping integration order]
	    = ∫ p(ω | x, D) log p(ω) dω                                        [resolving y integral]

**Comment by mjzhu-p** [comment]
Thank you! It is clear now.

**Comment by bayesoptbook** [comment]
Great!

**Comment by mjzhu-p** [comment]
Sorry, I just had a second look and realized that it seems the final result  $∫ p(ω | x, D) log p(ω) dω $ coincides with my initial question, as it is conditioned on $x$ and $D$, therefore, $D'$?

**Comment by bayesoptbook** [comment]
The operation we are performing is to compute the expected marginal gain in utility when moving from D → D ∪ (x, y) = D'. This is an expectation wrt y | x, D (note we do not condition on D' only x and D):

    E[u(D') - u(D) | x, D]
	      = E[u(D') | x, D] - E[u(D) | x, D].

For the first term, we write:

    u(D') = D_KL[p(ω | D') || p(ω)] 
          = ∫ p(ω | D') [log p(ω | D') / p(ω)] dω
          = ∫ p(ω | D') [log p(ω | D') - log p(ω)] dω
          = ∫ p(ω | D') log p(ω | D') dω
          - ∫ p(ω | D') log p(ω) dω.

Now

    E[u(D') | x, D] = E[ ∫ p(ω | D') log p(ω | D') dω | x, D ]
                    - E[ ∫ p(ω | D') log p(ω) dω | x, D ].

The first term appears unaltered at the top of the marginal note and the second term simplifies as above.

**Comment by mjzhu-p** [comment]
Thanks for the reply and your patience. 

I realized the difference between D' and x and D after performing the derivation again. Thanks for the further clarification and sorry about that.

**Comment by bayesoptbook** [comment]
Happy to help!

**Comment by JoonHyeok-hozy-Kim** [comment]
Thanks for the clarification. I had the same confusion and your reply was very helpful : )
