### ISSUE TITLE
Reproducing figure

### ISSUE THREAD

**Issue by thierrymoudiki** [bayesoptbook/bayesoptbook.github.io#52]
Not an issue: how to reproduce figures 11.12 and 11.13 please? (If possible).

Thanks

**Comment by bayesoptbook** [comment]
I wrote a pretty low-level implementation that used exhaustive Gauss-Hermite quadrature plus direct computation of the hypervolume improvement given x and samples of {y}. It sufficed for this figure but is not the kind of thing you'd want to do in a practical setting.
