### ISSUE TITLE
Notation of $\phi$ in Chapter 8

### ISSUE THREAD

**Issue by mjzhu-p** [bayesoptbook/bayesoptbook.github.io#53]
Thank you for the nice book on BO

In Eqn (8.9), p.159, and several other equations in the same chapter, $\phi$ is used to denote 
- the function evaluation $\phi = f(x)$, and
- the PDF of standard normal distribution $\phi\left(\frac{\mu-\phi^*}{\sigma}\right)$

which can be a bit confusing. 

It may be better to replace $\phi$ for the standard normal PDF with $\varphi$

**Comment by bayesoptbook** [comment]
I apologize for the confusion, and your solution is indeed elegant. Note that the standard normal pdf case will always appear with an argument, whereas the function value case will not.

If there's ever an edition 2 I will take your advice in mind.
