### ISSUE TITLE
Add some preliminary information for Chapter 8

### ISSUE THREAD

**Issue by mjzhu-p** [bayesoptbook/bayesoptbook.github.io#54]
When introducing Chapter 8, it may be helpful to direct to future chapters (if relevant) or include some preliminary information regarding the general solving procedure of the maximization problem of the acquisition function before diving into details.

This is because, for people who are not familiar with numerical solvers or practical implementation details, the assumption of a given and fixed $x$ (noted after eqn (8.3) on p.157) may be confusing. Understanding this assumption is important to grasp the ideas in this chapter. Also, we haven't discussed specific solving approaches for the maximization problem of the acquisition function until this chapter (I may have missed it), although it is a common practice using iterative solvers.

Sorry if I had some misunderstandings. Thank you.

**Comment by bayesoptbook** [comment]
Thank you for the suggestion but I'm afraid it's too late for these edits to be made. If there's a second edition I will come back to the recommendation.

However, you can regard the "given and fixed _x_" comment as simply saying that α(_x_; D) is a function of _x_, and we will show how to compute its value for any arbitrary _x_. Which should be sufficient for anything you want to do with the whole function.

**Comment by mjzhu-p** [comment]
Thanks for the reply, and yes, it is a valid point. I was thinking more from a motivational point of view, and connection to the whole framework.

**Comment by bayesoptbook** [comment]
I truly appreciate the feedback and think it's a great recommendation! I simply can no longer act on it post publication.

Thanks for all your recent feedback!
